kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: url-watcher
subjects:
- kind: ServiceAccount
  name: url-watcher
roleRef:
  kind: Role
  name: url-watcher
  apiGroup: rbac.authorization.k8s.io
