apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host:  postman-echo.com
      http:
        paths:
          - path: /get?foo1=bar1&foo2=bar2
            backend:
              serviceName: service1
              servicePort: 8888