// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.Watcher":       schema_pkg_apis_urlwatcher_v1alpha1_Watcher(ref),
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherSpec":   schema_pkg_apis_urlwatcher_v1alpha1_WatcherSpec(ref),
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherStatus": schema_pkg_apis_urlwatcher_v1alpha1_WatcherStatus(ref),
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_Watcher(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Watcher is the Schema for the watchers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherSpec", "managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.WatcherStatus"},
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_WatcherSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatcherSpec defines the desired state of Watcher",
				Properties: map[string]spec.Schema{
					"size": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"foo": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
				},
				Required: []string{"size", "foo"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_WatcherStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatcherStatus defines the observed state of Watcher",
				Properties: map[string]spec.Schema{
					"nodes": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"nodes"},
			},
		},
		Dependencies: []string{},
	}
}
