// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcher":       schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcher(ref),
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherSpec":   schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcherSpec(ref),
		"managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherStatus": schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcherStatus(ref),
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcher(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UrlWatcher is the Schema for the urlwatchers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherSpec", "managedkube.com/url-watcher/pkg/apis/urlwatcher/v1alpha1.UrlWatcherStatus"},
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcherSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UrlWatcherSpec defines the desired state of UrlWatcher",
				Properties: map[string]spec.Schema{
					"size": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"foo": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
				},
				Required: []string{"size", "foo"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_urlwatcher_v1alpha1_UrlWatcherStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UrlWatcherStatus defines the observed state of UrlWatcher",
				Properties: map[string]spec.Schema{
					"nodes": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"nodes"},
			},
		},
		Dependencies: []string{},
	}
}
